services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    container_name: postgres
    build: ./postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vectordb

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:80"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  llm_service:
    container_name: llm_service
    build: ./llm_service
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./llm_service:/app
      
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  redis_data:
  redis2_data: